name: Deploy Pages from artifact (Base64 via Gist)

on:
  repository_dispatch:
    types: [publish-cohorts]
  workflow_dispatch:

permissions:
  pages: write
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Debug payload
        run: |
          echo "artifact_url: ${{ github.event.client_payload.artifact_url }}"

      - name: Check artifact_url
        run: |
          test -n "${{ github.event.client_payload.artifact_url }}" \
            || (echo "::error::artifact_url is empty" && exit 1)

      - name: Download Base64 bundle
        run: |
          curl -fsSL "${{ github.event.client_payload.artifact_url }}" -o dist.zip.b64
          test -s dist.zip.b64

      - name: Extract GIST_ID from artifact_url
        id: extract
        run: |
          url="${{ github.event.client_payload.artifact_url }}"
          # Works with both formats:
          #  - https://gist.githubusercontent.com/<user>/<id>/raw/dist.zip.b64
          #  - https://gist.githubusercontent.com/<id>/raw/dist.zip.b64
          id="$(echo "$url" | sed -E 's#https?://gist.githubusercontent.com/([^/]+/)?([0-9a-fA-F]+).*#\2#')"
          if [ -z "$id" ] || [ "$id" = "$url" ]; then
            echo "::warning ::Could not parse Gist ID from artifact_url"
          fi
          echo "gist_id=$id" >> "$GITHUB_OUTPUT"
          echo "GIST_ID=$id"  >> "$GITHUB_ENV"
          echo "Parsed GIST_ID: $id"

      - name: Delete Gist after download (optional)
        if: ${{ secrets.GIST_TOKEN != '' && steps.extract.outputs.gist_id != '' }}
        run: |
          curl -s -X DELETE \
            -H "Authorization: token ${{ secrets.GIST_TOKEN }}" \
            "https://api.github.com/gists/${{ steps.extract.outputs.gist_id }}" \
            -o /dev/null -w "%{http_code}\n" || true

      - name: Decode -> dist.zip and unzip into docs/
        run: |
          base64 -d dist.zip.b64 > dist.zip
          rm -rf docs
          mkdir -p docs
          unzip -q dist.zip -d docs

      - name: Add .nojekyll and minimal index.html
        run: |
          touch docs/.nojekyll
          if [ ! -f docs/index.html ]; then
            cat > docs/index.html <<'HTML'
          <!doctype html><meta charset="utf-8"><title>Diamonds Config CDN</title>
          <p>OK.</p>
          HTML
          fi

      - name: Show files to be deployed
        run: |
          echo "---- tree docs (max 2 levels) ----"
          find docs -maxdepth 2 -type f -print

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4